# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

In [1]:
my_list = [1, 2, 3]

In [2]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
mat = np.array(my_mat)

In [8]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0, 11)         # Similar to python range function

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros(5)        # 1-D vector containing all zeroes

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros([5,5])         # 2-D matrix containing all zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(5)            # 1-D Vector containing all ones

array([1., 1., 1., 1., 1.])

In [20]:
np.ones([3,4])              # 2-D Vector containing all ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.linspace(0, 5, 10)        # Return evenly spaced numbers over a specified interval.

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [26]:
np.linspace(0, 5, 6)

array([0., 1., 2., 3., 4., 5.])

In [ ]:
np.eye(5)          # Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.random.rand(5)    # Random values in a given shape. Here 1-D

array([0.81497382, 0.5039597 , 0.86441725, 0.21441593, 0.95608018])

In [31]:
np.random.rand(5,5)      # Random values in a given shape. Here 2-D

array([[0.16981973, 0.61103081, 0.74691542, 0.31434114, 0.35392431],
       [0.28698827, 0.83231805, 0.90997591, 0.82561767, 0.44325881],
       [0.51650604, 0.84802954, 0.12765782, 0.3504348 , 0.27777736],
       [0.29231483, 0.08413258, 0.53715767, 0.08944101, 0.41982974],
       [0.2338963 , 0.32435563, 0.91956555, 0.34726663, 0.48563326]])

In [33]:
np.random.randn(2)   # Return a sample (or samples) from the "standard normal" distribution.

array([-0.11991808, -0.69680557])

In [34]:
np.random.randn(4,4)

array([[ 0.74505198, -0.40707938,  1.63990948,  2.4913962 ],
       [ 2.49651979,  0.59206017, -0.30663042, -0.06519756],
       [-0.30586336, -0.07344593,  0.49676496,  0.46038063],
       [-0.34903032, -1.27712374,  0.75114351,  1.46232389]])

In [ ]:
np.random.randint(1, 100)

# Return random integers from low (inclusive) to high (exclusive).
# Return random integers from the "discrete uniform" distribution of the specified dtype in the "half-open" interval [low, high). If high is None (the default), then results are from [0, low).

63

In [ ]:
np.random.randint(1, 100, 10)

array([ 4, 72, 34, 75, 48, 37, 85, 81, 12, 95], dtype=int32)

In [38]:
# Attributes and Methods of an array

In [39]:
arr = np.arange(25)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
ranarr = np.random.randint(0, 50, 10)

In [42]:
ranarr

array([49, 27, 44,  0, 24, 32, 21, 39, 13, 46], dtype=int32)

In [47]:
arr.reshape(5, 5)         # Used to reshape our array into a desired shape that we want. Here, change a 1-D Vector into 5x5 Matrix
# It should follow No. of elements in 1-D Vector = No. of rows x No. of columns in 2-D Matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
ranarr

array([49, 27, 44,  0, 24, 32, 21, 39, 13, 46], dtype=int32)

In [49]:
ranarr.max()

np.int32(49)

In [50]:
ranarr.min()

np.int32(0)

In [51]:
ranarr.argmax()

np.int64(0)

In [52]:
ranarr.argmin()

np.int64(3)

In [55]:
arr.shape

(25,)

In [56]:
ranarr.shape

(10,)

In [57]:
arr.reshape(5,5).shape

(5, 5)

In [58]:
arr.dtype

dtype('int64')

In [64]:
from numpy.random import randint as ri           # Shortcut if I don't want to write the same thing again and again

In [65]:
temp = ri(5)

In [66]:
temp

2