NumPy Indexing and Selection

In [2]:
import numpy as np

In [3]:
arr = np.arange(0, 11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [6]:
#Get a value at an index
arr[8]

np.int64(8)

In [7]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[:4]

array([0, 1, 2, 3])

In [9]:
arr[:6:2]

array([0, 2, 4])

In [10]:
arr[2:10:2]

array([2, 4, 6, 8])

In [11]:
arr[::3]

array([0, 3, 6, 9])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [ ]:
#Setting a value with index range (Broadcasting)
arr[0:5] = 100

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
arr = np.arange(0, 11)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
slice_of_arr = arr[0:6]

In [17]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [18]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [19]:
slice_of_arr[:] = 99

In [20]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [25]:
arr         # Here, we can observe that by changing the values in slice_of_arr, the values automatically gets changed in the main array.
# This means that here, the data is not copied separately rather it is just a view of the original array. 
# Numpy does this to avoid memory issues with very large arrays

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [27]:
# For the copy, what we can do is separately make a copy of the array
arr_copy = arr.copy()

In [28]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [29]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [33]:
arr_copy[0:6] = np.arange(0,6)

In [34]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [9]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [10]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
#Indexing row
arr_2d[0]

array([ 5, 10, 15])

In [22]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[0][0]

np.int64(5)

In [23]:
# Getting individual element value
arr_2d[0,0]

np.int64(5)

In [27]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [31]:
arr_2d[0:2,1:3]

array([[10, 15],
       [25, 30]])

In [ ]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [35]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [37]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [38]:
arr_2d[2,0:3]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [54]:
#Set up matrix
arr2d = np.zeros((10,10))

In [55]:
#Length of array
arr_length = arr2d.shape[1]

In [56]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [57]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [58]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Conditional Selection
To use brackets for selection based off of comparison operators.

In [39]:
narr = np.arange(1, 11)

In [40]:
narr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
bool_arr = narr > 5

In [43]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [45]:
narr[bool_arr]       # Got the values that has only true in this.

array([ 6,  7,  8,  9, 10])

In [46]:
# We can also do it directly in one single step i.e.
narr[narr > 5]

array([ 6,  7,  8,  9, 10])

In [47]:
narr[narr < 3]

array([1, 2])

In [50]:
arr_2d = np.arange(50).reshape(5,10)

In [51]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [52]:
arr_2d[1:4,5:9]

array([[15, 16, 17, 18],
       [25, 26, 27, 28],
       [35, 36, 37, 38]])