NumPy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[2]

np.int64(2)

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[:4]

array([0, 1, 2, 3])

In [9]:
arr[:6:2]

array([0, 2, 4])

In [10]:
arr[2:10:2]

array([2, 4, 6, 8])

In [11]:
arr[::3]

array([0, 3, 6, 9])

In [12]:
arr[0:5] = 100

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
arr = np.arange(0, 11)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
slice_of_arr = arr[0:6]

In [17]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [18]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [19]:
slice_of_arr[:] = 99

In [20]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [25]:
arr         # Here, we can observe that by changing the values in slice_of_arr, the values automatically gets changed in the main array.
# This means that here, the data is not copied separately rather it is just a view of the original array. 
# Numpy does this to avoid memory issues with very large arrays

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
# For the copy, what we can do is separately make a copy of the array
arr_copy = arr.copy()

In [28]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [29]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [33]:
arr_copy[0:6] = np.arange(0,6)

In [34]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])